blog/accounts/urls.py
from . import views 
from django.urls import path
app_name='accounts'
urlpatterns = [

     path('signup/', views.sign_up,name= "signup"),
     path('login/', views.log_in,name= "login"),
     path('logout/', views.log_out,name= "logout"),
     ]
    

blog/articles/urls.py
from . import views 
from django.urls import path
app_name= 'articles'

urlpatterns = [
    path('', views.articlelist,name= "list"),
    path('create/', views.articlecreate, name= "create"),

    path('<str:p>/', views.articledetails,name="details"),
    
    
] 

blog/blog/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static
from django.urls import re_path
from django.views.static import serve
from articles import views
urlpatterns = [
    path('admin/', admin.site.urls),
    path('articles/', include('articles.urls')),
    path('accounts/', include('accounts.urls')),
    path('',views.articlelist,name='home'),
    ]
    
# if settings.DEBUG:
#     urlpatterns += [
#         path('media/(?P<path>.*)$', serve, {
#             'document_root': settings.MEDIA_ROOT,
#         }),
#     ]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/articles/models.py
from django.db import models
import datetime
from  django.contrib.auth.models import User


class Article(models.Model):

	title=models.CharField(max_length=100)
	slug=models.SlugField()
	body=models.TextField()
	date=models.DateTimeField(auto_now_add=True)
	thumb=models.ImageField(default='default.png',blank=True)
	author=models.ForeignKey(User,default=None,on_delete=models.CASCADE)

	def __str__(self):
		return self.title
	def snippet(self):
		return self.body[:50]+'...'
	

# Create your models here.

blog/articles/forms.py
from django import forms
from . import models
class CreateArticle(forms.ModelForm):
	class Meta:
		model=models.Article
		fields=['title','slug','body','thumb']

blog/accounts/views.py
from django.shortcuts import render,redirect
from django.contrib.auth.forms import UserCreationForm,AuthenticationForm
from django.contrib.auth import login,logout
def sign_up(request):
	if request.method=='POST':
		form=UserCreationForm(request.POST)
		if form.is_valid():
			user=form.save()
			login(request,user)
			return redirect("articles:list")
	else:
		form=UserCreationForm()
	return render(request,'accounts/sign_up.html',{'form':form})

def log_in(request):
	if request.method=='POST':
		form=AuthenticationForm(data=request.POST)
		if form.is_valid():
			user=form.get_user()
			login(request,user)
			if 'next' in request.POST:
				return redirect(request.POST.get('next'))
			else:	
				return redirect("articles:list")
		


	else:
		form=AuthenticationForm()
	return render(request,'accounts/login.html',{'form':form})
def log_out(request):
	if request.method=='POST':
		logout(request)
		return redirect("articles:list")



# Create your views here.

blog/articles/views.py
from django.shortcuts import render ,redirect 
from .models import Article
from django.http import HttpResponse
from django.contrib.auth.decorators import login_required
from . import forms

def articlelist(request):
	articles=Article.objects.all().order_by('date')
	return render(request,'articles/article_list.html',{ 'art': articles})

def articledetails(request,p):
	article=Article.objects.get(slug=p)
	return render(request,'articles/article_details.html',{ 'art': article})

@login_required(login_url= "/accounts/login/")
def articlecreate(request):
	if request.method=='POST':
		form=forms.CreateArticle(request.POST,request.FILES)
		if form.is_valid():
			instance=form.save(commit=False)
			instance.author=request.user
			instance.save()
			#save to db
			return redirect('articles:list')

	else:
		form=forms.CreateArticle()
	return render(request,'articles/article_create.html',{'form':form})

# Create your views here.

blog/accounts/templates/accounts/login.html
{% extends 'base_layout.html' %}
{% block content %}
<h1> Login</h1>
<form class="site-form" action="{% url 'accounts:login' %}" method="post">
	{% csrf_token %}
	{{form}}
	{% if request.GET.next %}
		<input type="hidden" name="next" value="{{request.GET.next}}">
	{% endif %}
	<input type="submit" value="Login">
</form>

{% endblock %}

blog/accounts/templates/accounts/sign_up.html
{% extends 'base_layout.html' %}
{% block content %}
<h1> Signup</h1>
<form class="site-form" action="/accounts/signup/" method="post">
	{% csrf_token %}
	{{form}}
	<input type="submit" value="Signup">
</form>

{% endblock %}

blog/articles/templates/articles/article_create.html
{% extends 'base_layout.html' %}
{% block content %}

 <div class="create-article">
	<h2> create an Awesome New Article </h2>
	<form class="site-form" action="{% url 'articles:create' %}" method="post" enctype="multipart/form-data">
		{%csrf_token%}
		{{form}}
		<input type="submit" value="Create">
	</form>

 </div>
 <script src="/static/slugify.js"></script>
 {% endblock %}

blog/articles/templates/articles/article_details.html
 
{% extends 'base_layout.html' %}
{% block content %}
<h1>Arricle List</h1>
 <div class="article-details">
 	<div class="article">

	  <div class="article">
	  	<img src= "{{art.thumb.url}}">
		<h2> {{ art.title }}</h2>
		<p>{{ art.body }}</p>
		<p>{{art.date}}</p>
	</div>
	</div>


	

 </div>
 {% endblock %}

blog/articles/templates/articles/article_list.html
 
{% extends 'base_layout.html' %}
{% block content %}
<h1>Article List</h1>
 <div class="articles">
	{% for article in art %} 

	  <div class="article">
		<h2> <a href="{% url 'articles:details' p=article.slug %}">{{ article.title }}</a></h2>
		<p>{{ article.snippet }}</p>
		<p>{{article.date}}</p>
		<p class="author" >added by {{article.author.username}}</p>
	</div>


	{% endfor %}

 </div>
 {% endblock %}

blog/templates/base_layout.html
<!DOCTYPE html>
<html>
<head>
	<title>Articles</title>
	<link rel="stylesheet" href="/static/style.css">
</head>
<body>
	
	
	
<header class="wrapper">
<h1> <a href="{% url 'home' %}"><img src= "/static/logo.png"></a></h1>
	<nav>
		<ul>
			{% if user.is_authenticated %}
				<li>
					<form class="logout-link" action="{% url 'accounts:logout' %}" method="post">
						{% csrf_token %}
						<button type="submit">Logout</button>
					</form>
				</li>
				<li><a href="{% url 'articles:create' %}" class="highlight">New Article</a></li>
				
			{% else %}
				<li><a href="{% url 'accounts:login' %}">Login</a></li>
				<li><a href="{% url 'accounts:signup' %}">Signup</a></li>
			{% endif %}

		</ul>
	</nav>
	</header>
	<div class="wrapper">
	{% block content %}
	{% endblock %}

</div>


</body>
</html>